### ISSUE TITLE
Add Kluent

### ISSUE THREAD

**Issue by FRedEnergy** [JavaBy/awesome-kotlin#20]
https://github.com/MarkusAmshove/Kluent

Kluent is a "Fluent Assertions" library written specifically for Kotlin. It uses the Infix-Notations and Extension Functions of Kotlin to provide a fluent wrapper around the JUnit-Asserts.

Even it doesn't have too much stars I think it's an interesting thing and deserves a place in this awesome list

**Comment by IRus** [comment]
For sure i will add it to list, thank you!
